### ISSUE TITLE
Highlights non-color array keys in Drupal PHP code

### ISSUE THREAD

**Issue by ilkka** [sergiirocks/vscode-ext-color-highlight#1]
For one reason or another, in Drupal, many predefined array keys start with a hash. This plugin highlights them if they happen to start with a string of characters that is a valid hex color, for example anything that starts with `#default`.

![2016-02-29 at 10 52](https://cloud.githubusercontent.com/assets/1549/13389806/50a29b00-ded3-11e5-89b6-bd2e6816a5aa.png)

**Comment by ilkka** [comment]
Probably it would be enough to just match a following non-word character [here](https://github.com/naumovs/vscode-ext-color-highlight/blob/7786b0b6edcab14760f9484d691ce059969d3950/src/lib/color-finder.js#L10)?

**Comment by andyparisi** [comment]
This also happens with CSS properties such as `white-space`. The word "white" is being picked up as a color, but it's not a color, but a property name.

![image](https://cloud.githubusercontent.com/assets/2438215/17900235/71f68a62-692c-11e6-815d-315d6872b17b.png)

**Comment by sergiirocks** [comment]
fixed in 1.3.0
