### ISSUE TITLE
dot highlight would be nice

### ISSUE THREAD

**Issue by geddski** [sergiirocks/vscode-ext-color-highlight#12]
similar to Atom:

![image](https://cloud.githubusercontent.com/assets/515722/20282018/249b0664-aa70-11e6-93d8-06c30a9efcaf.png)

**Comment by sqnkov** [comment]
@sergiirocks , a dot highlight would be awesome!

**Comment by guywald1** [comment]
+1

**Comment by GriNAME** [comment]
I like it too, but I think it should be done optional.

**Comment by sergiirocks** [comment]
Added in release 2.0.0

**Comment by geddski** [comment]
Nice! Thanks

**Comment by GriNAME** [comment]
Thanks))

**Comment by sqnkov** [comment]
@sergiirocks , there is a small issue.

We also get a rectangle beside the color.

![dotsq](https://cloud.githubusercontent.com/assets/9406520/24995023/ea176e88-2035-11e7-82a6-be402495bbe7.PNG)

**Comment by sergiirocks** [comment]
You should set these options to false in your user config
```json
{
  // Controls CSS validation and problem severities.
  // Enables or disables all validations
  "css.validate": true,

  // Enables or disables color decorators
  "css.colorDecorators.enable": false,
  "scss.colorDecorators.enable": false,
  // Enables or disables color decorators
  "less.colorDecorators.enable": false,

  // Enables or disables color decorators
  "json.colorDecorators.enable": false,
}
```

**Comment by sqnkov** [comment]
@sergiirocks , thank You. This even added a bit of speed to the editor itself...

**Comment by geddski** [comment]
it works great, thanks again @sergiirocks
