### ISSUE TITLE
support hex alpha

### ISSUE THREAD

**Issue by farfromrefug** [sergiirocks/vscode-ext-color-highlight#13]
Could you add support for hex alpha?
It s as simple as changing your regex to support length 4 and 8.

Thanks!

**Comment by sergiirocks** [comment]
Hey. It's not that obvious to support alpha values as the IDE background color differs from the background where it's used, therefore makes no sense.

**Comment by farfromrefug** [comment]
@sergiirocks "makes no sense" does not seem like a great answer to me...
Sublime Text does that really well. And it works with any background.
<img width="296" alt="screen shot 2016-12-06 at 15 49 45" src="https://cloud.githubusercontent.com/assets/655344/20929864/c7ceb8c8-bbcb-11e6-8d0c-60d4fa882ec6.png">
Anyway, your project, you decide ...

**Comment by farfromrefug** [comment]
and by the way you already supported for rgba ...

**Comment by sergiirocks** [comment]
Sorry if it sounded rude to you, didn't mean that at all. 
I just didn't see a valid reason for that. Now when you showed me a screenshot I actually consider to do that

**Comment by sergiirocks** [comment]
done in 1.3.0

**Comment by farfromrefug** [comment]
@sergiirocks it does not work perfectly yet. I can't get it work with 8 and 4 hexes:
<img width="409" alt="screen shot 2016-12-07 at 07 48 50" src="https://cloud.githubusercontent.com/assets/655344/20957714/a16d90d8-bc51-11e6-8b37-ab282377e9fd.png">
Could it be you are sending ```match[0]``` to Color which does not support alpha in hex?
BTW there is another nice and small lib that supports it all: [tinycolor](https://github.com/bgrins/TinyColor)

**Comment by sergiirocks** [comment]
Did you update to 1.3.0?

**Comment by farfromrefug** [comment]
@sergiirocks Yes i am using 1.3.0
