### ISSUE TITLE
does not highlight alpha ff, example #f92e8afe ok, #f92e8aff not

### ISSUE THREAD

**Issue by ADrone** [sergiirocks/vscode-ext-color-highlight#16]
not a huge issue, ff alpha is unnecessary anyway so just delete ff, and works.

**Comment by sergiirocks** [comment]
Seems like not an issue at all. FF is 255 which is completely transparent -> no bg color applied, right?

**Comment by ADrone** [comment]
I think you are right, it is not an issue.
FF is full alpha, so using alpha value FF does not make sense. #F92E8AFF = #F92E8A
I will either use an alpha or just delete the value.


-Chris
