### ISSUE TITLE
white in white-space is colored

### ISSUE THREAD

**Issue by Almenon** [sergiirocks/vscode-ext-color-highlight#18]
```css
#text{
    white-space: pre-wrap;
}
```

White is colored white, but it should not be colored at all.  White-space is the only CSS property with a color in its name, so (_for now!_) it would be safe to just append a negative lookahead for the dash in white-space (?!-) to the regex, like so:

```javascript
const colorWeb = new RegExp('\\(' + preparedRePart + '\\)(?!-)', 'g');
```

see [https://regex101.com/r/niLgcc/1](https://regex101.com/r/niLgcc/1) for an example of the negative lookahead.

And yes, I'm aware I can turn off word highlighting.  Just thought I'd let you know of the problem :)

**Comment by sergiirocks** [comment]
Fixed in 2.1.0
