### ISSUE TITLE
Shows colors where you don't need to

### ISSUE THREAD

**Issue by GriNAME** [sergiirocks/vscode-ext-color-highlight#22]
Shows colors everywhere it sees color names.
![image](https://cloud.githubusercontent.com/assets/8003716/23890383/b436491a-08a2-11e7-955e-f000739ae487.png)

Maybe you should make a rule when the color name is inside another title don't show the color

**Comment by sergiirocks** [comment]
set the option editor option "color-highlight.matchWords" to false

**Comment by GriNAME** [comment]
Oops.. Sorry and thanks))
