### ISSUE TITLE
Please consider adding a CHANGELOG.md

### ISSUE THREAD

**Issue by bbugh** [sergiirocks/vscode-ext-color-highlight#23]
Updates in VS Code don't tell us what has changed. You do have it in the readme, but enabling this feature follows the common pattern of putting in a CHANGELOG.md. 

![image](https://cloud.githubusercontent.com/assets/438465/24155383/b072007e-0e21-11e7-8868-de223c1d6445.png)

Please consider adding a CHANGELOG.md

**Comment by sergiirocks** [comment]
Ah I see. Currently the changelist is maintained in the README.md

**Comment by sergiirocks** [comment]
Added in release 2.0.0
