### ISSUE TITLE
Colors non-colors

### ISSUE THREAD

**Issue by bobrocke** [sergiirocks/vscode-ext-color-highlight#25]
Hex sequences that are not colors get highlighted, too. Like this:

![noncolor](https://cloud.githubusercontent.com/assets/2962426/25024666/c5d8424a-206c-11e7-9671-d082bb76776c.jpeg)

**Comment by sergiirocks** [comment]
this is actually can be a color with opacity (valid for setups with [postcss](https://github.com/postcss/postcss-color-hex-alpha)). You can configure the languages that are affected by the plugin in the options

**Comment by bobrocke** [comment]
True. But the context suggests that it should not be highlighted.

**Comment by sergiirocks** [comment]
Yeah, I'll try to fix that.

**Comment by sergiirocks** [comment]
Fixed in 2.1.0
