### ISSUE TITLE
Feature Request: Setting to disabled colors in scrollbar

### ISSUE THREAD

**Issue by peterph-am** [sergiirocks/vscode-ext-color-highlight#6]
I love this extension, especially with the new background setting.

However, I've found that it adds some sort of mini map in the scrollbar of all highlighted colors in my file:

![Uploading Screen Shot 2016-08-12 at 12.09.03 PM.png…]()

Can we get a setting to be able to disable this feature? I find it distracting and unnecessary.

**Comment by Septh** [comment]
I came here with exactly the same question in mind :)

**Comment by ADrone** [comment]
I got here with the same question, it's a great way to work with colors, but clogged up the scroll bar.

VScode calls the scrollbar ruler, once I figured that out I thought I should share the update, PR made.
Also here is a link to the compiled files until the official extension is updated: https://github.com/ADrone/vscode-ext-color-highlight-compiled

Thanks.

**Comment by sergiirocks** [comment]
I'll review that tomorrow, thanks!

**Comment by Nejik** [comment]
Came here with same question, sergii, can you look ADrone's PR?

**Comment by sergiirocks** [comment]
Addressed in the latest version

**Comment by ADrone** [comment]
thanks!

**Comment by kruzyk** [comment]
so... how I can use this?

**Comment by kruzyk** [comment]
ok, so I found it exploring extension.js :)

in settings.json add:
`"color-highlight.markRuler": false`

**Comment by kolchurinvv** [comment]
> To make this work you have to add in settings.json: `"color-highlight.markRuler": false`

Could you please add this to the readme file?
