### ISSUE TITLE
Some colors not detected

### ISSUE THREAD

**Issue by bartold3ak** [sergiirocks/vscode-ext-color-highlight#67]
Hi! 
Shortly after installing this extension I noticed that not all colors are detected. 

Example: 
`color: #f5f5f5; // detected`
`color: #212121; // not detected`
`color: #121212; // not detected`

**Comment by alexandreramosdev** [comment]
I think it is because of your background color theme. Test changes the background color of your theme!

**Comment by bartold3ak** [comment]
Yes! Thank you!
