### ISSUE TITLE
Feature request: Add the highlight functionality to the color variables for sass and less

### ISSUE THREAD

**Issue by agmuntean** [sergiirocks/vscode-ext-color-highlight#7]
I like the extension. 
I was wondering if possible the color variables to inherit the hex highlight, this would be very helpful for sass/less projects.

**Comment by 256k** [comment]
i know there is a lot of confusion when people say sass, so unless this was the intended meaning of the OP, id also suggest for indented Sass (not just SCSS)

**Comment by abea** [comment]
In case helpful, the [Atom plugin Pigments](https://github.com/abe33/atom-pigments/) does this. Something I miss dearly from using Atom.

**Comment by ArkhipovK** [comment]
+1

**Comment by bobrocke** [comment]
Yes, this would be helpful and cool.

**Comment by sergiirocks** [comment]
I'm doing that. After refactoring it it much easier to implement that and this feature will be available in the next update.

**Comment by ArkhipovK** [comment]
sergiirocks, will this feature take imports (multifile) into account?

**Comment by sergiirocks** [comment]
First iteration definitely won't, but this is on my list

**Comment by sergiirocks** [comment]
Fixed in 2.1.0

**Comment by Jordan4jc** [comment]
Any update on when imported files will be supported with this? I see if the variable is defined in the same file it works but variables defined in an imported file are not color highlighted.
