### ISSUE TITLE
Wrong highlighting in CSS

### ISSUE THREAD

**Issue by Alex-Sokolov** [sergiirocks/vscode-ext-color-highlight#9]
Have some CSS:
![wrong_highlight](https://cloud.githubusercontent.com/assets/4497128/18865649/00297234-84a5-11e6-8890-5c7d0fbc3440.PNG)
![default](https://cloud.githubusercontent.com/assets/4497128/18867646/c195cd48-84ad-11e6-9a38-40066d164b69.PNG)

Extension highlight part of selector `#bac`. I think search must be inside `{}` and exclude selector names

Using:
- Visual Studio Code 1.5.3
- Color Highlight 1.2.1

**Comment by sergiirocks** [comment]
hey, thanks for the report, I'll take a look during this week

**Comment by sergiirocks** [comment]
fixed in 1.3.0
